export default function handler(req, res) { 
const players = [
    {
      firstName: 'Lev',
      lastName: 'Yashin',
      birthDate: '1929-10-22',
      nationalTeam: 'URSS',
      matches: 150,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_the_Soviet_Union.svg',
      photo: 'https://i.ebayimg.com/images/g/Gs8AAOSwgGlewp96/s-l1200.jpg',
    },
    {
      firstName: 'Gianluigi',
      lastName: 'Buffon',
      birthDate: '1978-01-28',
      nationalTeam: 'Italie',
      matches: 176,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: '',
    },
    
    {
      firstName: 'Iker',
      lastName: 'Casillas',
      birthDate: '1981-05-20',
      nationalTeam: 'Espagne',
      matches: 167,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Spain.svg',
      photo: '',
    },
    {
      firstName: 'Manuel',
      lastName: 'Neuer',
      birthDate: '1986-03-27',
      nationalTeam: 'Allemagne',
      matches: 116,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg',
    },
    {
      firstName: 'Peter',
      lastName: 'Schmeichel',
      birthDate: '1963-11-18',
      nationalTeam: 'Danemark',
      matches: 129,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Denmark.svg',
      photo: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Peter_Schmeichel_2018.jpg',
    },
    {
      firstName: 'Angelo',
      lastName: 'Peruzzi',
      birthDate: '1970-02-16',
      nationalTeam: 'Italie',
      matches: 31,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: '',
    },
    {
      firstName: 'Edwin',
      lastName: 'van der Sar',
      birthDate: '1970-10-29',
      nationalTeam: 'Pays-Bas',
      matches: 130,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg',
      photo: 'https://upload.wikimedia.org/wikipedia/commons/1/19/Edwin_van_der_Sar_%282015%29.jpg',
    },
    {
      firstName: 'Kasper',
      lastName: 'Schmeichel',
      birthDate: '1986-11-05',
      nationalTeam: 'Danemark',
      matches: 72,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Denmark.svg',
      photo: '',
    },
    {
      firstName: 'Alisson',
      lastName: 'Becker',
      birthDate: '1992-10-02',
      nationalTeam: 'Brésil',
      matches: 57,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg',
      photo: '',
    },
    {
      firstName: 'Dida',
      lastName: '',
      birthDate: '1973-10-07',
      nationalTeam: 'Brésil',
      matches: 91,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg',
      photo: '',
    },
    {
      firstName: 'Bodo',
      lastName: 'Köpke',
      birthDate: '1962-06-08',
      nationalTeam: 'Allemagne',
      matches: 59,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg',
      photo: '',
    },
    {
      firstName: 'Nasser',
      lastName: 'Drid',
      birthDate: '1971-04-10',
      nationalTeam: 'Algérie',
      matches: 70,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg',
      photo: '',
    },
    {
      firstName: 'Mehdi',
      lastName: 'Cerbah',
      birthDate: '03/01/1953',
      nationalTeam: 'Algérie',
      matches: 62,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg',
      photo: '',
    },
 
      {
        firstName: 'Badou',
        lastName: 'Zaki',
        birthDate: '1959-04-02',
        nationalTeam: 'Maroc',
        matches: 124,
        goals: 0,
        flag: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Flag_of_Morocco.svg',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/1/19/Badou_Zaki.jpg',
      },
      {
        firstName: 'Ngalula',
        lastName: 'Nkono',
        birthDate: '1956-11-25',
        nationalTeam: 'Cameroun',
        matches: 94,
        goals: 0,
        flag: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Flag_of_Cameroon.svg',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Nkono.JPG',
      },
      {
        firstName: 'Antoine',
        lastName: 'Bell',
        birthDate: '1964-11-15',
        nationalTeam: 'Cameroun',
        matches: 25,
        goals: 0,
        flag: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Flag_of_Cameroon.svg',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Antoine_Bell.JPG',
      },
      {
        firstName: 'Essam',
        lastName: 'El-Hadary',
        birthDate: '1973-01-15',
        nationalTeam: 'Égypte',
        matches: 159,
        goals: 0,
        flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Essam_El-Hadary.jpg',
      },
    
    
    {
      firstName: 'Sebastiano',
      lastName: 'Rossi',
      birthDate: '1964-01-20',
      nationalTeam: 'Italie',
      matches: 28,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: '',
    },
    {
      firstName: 'Gianluca',
      lastName: 'Pagliuca',
      birthDate: '1966-12-18',
      nationalTeam: 'Italie',
      matches: 39,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: '',
    },
    {
      firstName: 'Francesco',
      lastName: 'Toldo',
      birthDate: '1971-12-02',
      nationalTeam: 'Italie',
      matches: 28,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: '',
    },
    {
      firstName: 'Dino',
      lastName: 'Zoff',
      birthDate: '1942-02-28',
      nationalTeam: 'Italie',
      matches: 112,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: '',
    },
    
 
    
    ];
    
 
  res.status(200).json(players);
}