export default function handler(req, res) { 
const players = [
    {
      firstName: 'Lev',
      lastName: 'Yashin',
      birthDate: '1929-10-22',
      nationalTeam: 'URSS',
      matches: 150,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_the_Soviet_Union.svg',
      photo: 'https://i.ebayimg.com/images/g/Gs8AAOSwgGlewp96/s-l1200.jpg',
    },
    {
      firstName: 'Gianluigi',
      lastName: 'Buffon',
      birthDate: '1978-01-28',
      nationalTeam: 'Italie',
      matches: 176,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: 'https://media.gettyimages.com/id/109339900/fr/photo/lecce-italy-gigi-buffon-of-juventus-before-the-serie-a-match-between-lecce-and-juventus-fc-at.jpg?s=2048x2048&w=gi&k=20&c=Eqv-djsVZrzFd9TvkFDdY3yS4SIgQadSdqO7csOq9j8=',
    },
    {
      firstName: 'Dino',
      lastName: 'Zoff',
      birthDate: '1942-02-28',
      nationalTeam: 'Italie',
      matches: 112,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: 'https://media.gettyimages.com/id/468133770/fr/photo/rome-italy-italy-goalkeeper-dino-zoff-in-action-during-an-international-match-circa-1976-zoff.jpg?s=2048x2048&w=gi&k=20&c=4YR6fvGcei_2M0_FY0B8GvAZmTo_pmgMeLVkjpaUB9E='    },
    
    {
      firstName: 'Iker',
      lastName: 'Casillas',
      birthDate: '1981-05-20',
      nationalTeam: 'Espagne',
      matches: 167,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Spain.svg',
      photo: 'https://media.gettyimages.com/id/102811090/fr/photo/johannesburg-south-africa-iker-casillas-captain-of-spain-celebrates-the-late-goal-by-andres.jpg?s=2048x2048&w=gi&k=20&c=rReBeweYXQKvd0T2Av0Hwe71g_ulmjVKWNlfM56JoBY=',
    },
    {
      firstName: 'Sebastiano',
      lastName: 'Rossi',
      birthDate: '1964-01-20',
      nationalTeam: 'Italie',
      matches: 28,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: 'https://media.gettyimages.com/id/78961783/fr/photo/13th-march-1994-italian-league-serie-a-sebastiano-rossi-ac-milan-goalkeeper.jpg?s=1024x1024&w=gi&k=20&c=rCx78Ib4BZF90C9yJwUv3DFS_ivHvIZ1Idj0VOKa7kY=',
    },
    {
      firstName: 'Gianluca',
      lastName: 'Pagliuca',
      birthDate: '1966-12-18',
      nationalTeam: 'Italie',
      matches: 39,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: 'https://media.gettyimages.com/id/644843616/fr/photo/gianluca-pagliuca-italie-irlande-coupe-du-monde-1994-photo-alain-gadoffre-icon-sport.jpg?s=1024x1024&w=gi&k=20&c=EUOnTtzCvUHTPDC11Ob81Fyb4paXQwg4eSJCZqS235c=',
    },
    {
      firstName: 'Francesco',
      lastName: 'Toldo',
      birthDate: '1971-12-02',
      nationalTeam: 'Italie',
      matches: 28,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: 'https://media.gettyimages.com/id/52916662/fr/photo/amsterdam-netherlands-em-euro-2000-halbfinale-amsterdam-italien-niederlande-n-e-3-1-torwart.jpg?s=2048x2048&w=gi&k=20&c=yeQna3djZo9BlODrLd2Vb2I6WjUB7viuOMYqK8gr-zg=',
    },
   
    {
      firstName: 'Manuel',
      lastName: 'Neuer',
      birthDate: '1986-03-27',
      nationalTeam: 'Allemagne',
      matches: 116,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg',
      photo:'https://media.gettyimages.com/id/1431780081/fr/photo/dortmund-germany-manuel-neuer-of-bayern-m%C3%BCnchen-reacts-during-the-bundesliga-match-between.jpg?s=2048x2048&w=gi&k=20&c=4hpZEYe1a_1FYQPcliaps7qgGfUUAv4BXuwJNRidP4w='
    },
    {
      firstName: 'Peter',
      lastName: 'Schmeichel',
      birthDate: '1963-11-18',
      nationalTeam: 'Danemark',
      matches: 129,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Denmark.svg',
      photo: 'https://media.gettyimages.com/id/1641601/fr/photo/manchester-united-keeper-peter-schmeichel-celebrates-a-goal-in-the-uefa-champions-league-semi.jpg?s=2048x2048&w=gi&k=20&c=ONQLREP434A4Ut-30YZguJYwscB3p5dZWTquFyukJBo=',
    },
    {
      firstName: 'Angelo',
      lastName: 'Peruzzi',
      birthDate: '1970-02-16',
      nationalTeam: 'Italie',
      matches: 31,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg',
      photo: 'https://media.gettyimages.com/id/1640094/fr/photo/angelo-peruzzi-of-juventus-in-action-during-the-italian-serie-a-match-against-inter-milan-at-the.jpg?s=2048x2048&w=gi&k=20&c=asX3YcdQkY1zzv_2VaSwtpgzo-Wx3DCLZSnsXBmAeXQ=',
    },
    {
      firstName: 'Edwin',
      lastName: 'van der Sar',
      birthDate: '1970-10-29',
      nationalTeam: 'Pays-Bas',
      matches: 130,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg',
      photo : " https://media.gettyimages.com/id/111755864/fr/photo/london-england-edwin-van-der-sar-of-manchester-united-celebrates-as-wayne-rooney-scores-their.jpg?s=2048x2048&w=gi&k=20&c=9zEz5eRXT-EbwLCP7zaO5vBtCIqro8r5uClDutVHrBY="    },
   
    {
      firstName: 'Alisson',
      lastName: 'Becker',
      birthDate: '1992-10-02',
      nationalTeam: 'Brésil',
      matches: 57,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg',
      photo: '',
    },
    {
      firstName: 'Dida',
      lastName: '',
      birthDate: '1973-10-07',
      nationalTeam: 'Brésil',
      matches: 91,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg',
      photo: 'https://media.gettyimages.com/id/584930930/fr/photo/dortmund-germany-goalkeeper-dida-of-brazil-during-the-fifa-2006-world-cup-round-of-16-match.jpg?s=2048x2048&w=gi&k=20&c=jk_A7XwdAJcF3TP6uTXMlRrCli5NDnmrGwXT4OdwRZ4=',
    },
    {
      firstName: 'Bodo',
      lastName: 'Köpke',
      birthDate: '1962-06-08',
      nationalTeam: 'Allemagne',
      matches: 59,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg',
      photo: 'https://media.gettyimages.com/id/143320534/fr/photo/hamburg-germany-goalkeeper-coach-andreas-koepke-of-germany-poses-during-a-national-team.jpg?s=2048x2048&w=gi&k=20&c=T5tSR98ACOktff2yy7EvcXXPTck4N314_iHXY18d7bY=',
    },
    {
      firstName: 'Nasser',
      lastName: 'Drid',
      birthDate: '1971-04-10',
      nationalTeam: 'Algérie',
      matches: 70,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg',
      photo: '',
    },
    {
      firstName: 'Mehdi',
      lastName: 'Cerbah',
      birthDate: '03/01/1953',
      nationalTeam: 'Algérie',
      matches: 62,
      goals: 0,
      flag: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg',
      photo: '',
    },
 
      {
        firstName: 'Badou',
        lastName: 'Zaki',
        birthDate: '1959-04-02',
        nationalTeam: 'Maroc',
        matches: 124,
        goals: 0,
        flag: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Flag_of_Morocco.svg',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/1/19/Badou_Zaki.jpg',
      },
      {
        firstName: 'Ngalula',
        lastName: 'Nkono',
        birthDate: '1956-11-25',
        nationalTeam: 'Cameroun',
        matches: 94,
        goals: 0,
        flag: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Flag_of_Cameroon.svg',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Nkono.JPG',
      },
      {
        firstName: 'Antoine',
        lastName: 'Bell',
        birthDate: '1964-11-15',
        nationalTeam: 'Cameroun',
        matches: 25,
        goals: 0,
        flag: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Flag_of_Cameroon.svg',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Antoine_Bell.JPG',
      },
      {
        firstName: 'Essam',
        lastName: 'El-Hadary',
        birthDate: '1973-01-15',
        nationalTeam: 'Égypte',
        matches: 159,
        goals: 0,
        flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Essam_El-Hadary.jpg',
      },
    
    
    
    
 
    
    ];
    
 
  res.status(200).json(players);
}